---
###############################################################################
# SR-IOV Network Definition for workload (e.g. CNF DU with cu-plane)
# oran-fh-vfio + vlan 2001 + oran_fh_vfio 
###############################################################################
# NS = cnf-du
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: oran-fh-vfio
  namespace: openshift-sriov-network-operator
spec:
  resourceName: oran_fh_vfio
  networkNamespace: cnf-du
  vlan: 2001
  ipam: |-
    {}
  linkState: auto
  # spoofChk: "<spoof_check>"
  # maxTxRate: <max_tx_rate>
  # minTxRate: <min_rx_rate>
  vlanQoS: 7
  # trust: "<trust_vf>"
  # capabilities: <capabilities>