---
# Find the right NIC
# ls -l /sys/class/net/
# oc label node w2 ran.openshift.io/ptp="" ran.openshift.io/ptp-ran-du=""
# Configuration C3
apiVersion: ptp.openshift.io/v1
kind: PtpConfig
metadata:
  name: ptp-ran-du
  namespace: openshift-ptp
spec:
  profile:
    - name: "ptp-ran-du"
      interface: "ens1f1"
      ptp4lOpts: "-2 --summary_interval -4 -m -s -H"
      phc2sysOpts: "-a -r -n 24"
      #phc2sysOpts: "-s <intf name> -w -m -R 8 -n 24"
      ptp4lConf: |
        [global]
        #
        # Default Data Set
        #
        twoStepFlag 1
        #slaveOnly 1
        priority1 128
        priority2 128
        clockClass 248
        clockAccuracy 0xFE
        offsetScaledLogVariance 0xFFFF
        free_running 0
        freq_est_interval 1
        dscp_event 0
        dscp_general 0
        #dataset_comparison G.8275.x
        #G.8275.defaultDS.localPriority 128
        #G.8275.portDS.localPriority 128
        #
        # Port Data Set
        #
        logAnnounceInterval -3
        logSyncInterval -4
        logMinDelayReqInterval -4
        logMinPdelayReqInterval 0
        announceReceiptTimeout 3
        syncReceiptTimeout 100
        delayAsymmetry 0
        fault_reset_interval ASAP
        #fault_reset_interval 4
        neighborPropDelayThresh 20000000
        #
        # Run time options
        #
        assume_two_step 1
        logging_level 6
        path_trace_enabled 0
        follow_up_info 0
        hybrid_e2e 0
        tx_timestamp_timeout 100
        use_syslog 1
        verbose 0
        #summary_interval 0
        kernel_leap 1
        check_fup_sync 0
        #
        # Servo Options
        #
        pi_proportional_const 0.0
        pi_integral_const 0.0
        pi_proportional_scale 0.0
        pi_proportional_exponent -0.3
        pi_proportional_norm_max 1
        pi_integral_scale 0.5
        pi_integral_exponent 1
        pi_integral_norm_max 0.3
        step_threshold 0.0
        first_step_threshold 0.00002
        max_frequency 900000000
        clock_servo pi
        sanity_freq_limit 200000000
        ntpshm_segment 0
        #
        # Transport Options
        #
        transportSpecific 0x0
        ptp_dst_mac 01:1B:19:00:00:00
        p2p_dst_mac 01:80:C2:00:00:0E
        udp_ttl 1
        udp6_scope 0x0E
        uds_address /var/run/ptp4l
        #
        # Default Interface Options
        #
        #    clock_type OC
        network_transport L2
        delay_mechanism E2E
        time_stamping hardware
        tsproc_mode filter
        delay_filter moving_median
        delay_filter_length 50
        egressLatency 0
        ingressLatency 0
        boundary_clock_jbod 0
        #
        # Clock Description
        #
        productDescription ;;
        revisionData ;;
        manufacturerIdentity 00:00:00
        userDescription ;
        timeSource 0xA0
        domainNumber 24
  recommend:
    - profile: "ptp-ran-du"
      priority: 1
      match:
        - nodeLabel: "ran.openshift.io/ptp-ran-du"
